# build settings for netlify

# [build] and [build.environment] are defaults, will apply to all builds unless overridden in a context stanza below
[build]

  base = "site/"
  publish = "site/public/"

[build.environment]
  HUGO_VERSION = "0.37.1"

[context.deploy-preview]
  # this command builds draft content for deploy previews
  command = 'hugo -D && cp public/404/index.html public/404.html'

[context.branch-deploy]
  # this command builds draft content for deploy previews
  command = 'hugo -D  && cp public/404/index.html public/404.html'

[context.production]
  # drafts are excluded (no `-D` option to hugo) for prod build
  command = 'hugo && cp public/404/index.html public/404.html && mkdir -p ~/.ssh && echo -e "${SSH_KEY//_/\\n}" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa && ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@api.shift2bikes.org "cd /opt/shift-docs && ./shift pull"'


## domain redirects to serve from the CDN and canonicalize
## must be first redirects in this file!

[[redirects]]
  from = "https://shift2bikes.com/*"
  to = "https://www.shift2bikes.org/:splat" 
  status = 301
  force = true
[[redirects]]
  from = "https://www.shift2bikes.com/*"
  to = "https://www.shift2bikes.org/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://shifttobikes.com/*"
  to = "https://www.shift2bikes.org/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.shifttobikes.com/*"
  to = "https://www.shift2bikes.org/:splat"
  status =  301
  force = true
[[redirects]]
  from = "https://shifttobikes.com/*"
  to = "https://www.shift2bikes.org/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.shifttobikes.com/*"
  to = "https://www.shift2bikes.org/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://new.shift2bikes.org/*"
  to = "https://www.shift2bikes.org/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://pedalpalooza.org/*"
  to = "http://pedalpaloozamedia.wixsite.com/pedalpalooza"
  status = 302
  force = true
[[redirects]]
  from = "https://www.pedalpalooza.org/*"
  to = "http://pedalpaloozamedia.wixsite.com/pedalpalooza"
  status = 302
  force = true

# dynamic back end + event images stored over here.  Solves CORS problems to proxy.
[[redirects]]
  from = "/api/*"
  to = "https://api.shift2bikes.org/api/:splat"
  status = 200
[[redirects]]
  from = "/eventimages/*"
  to = "https://api.shift2bikes.org/eventimages/:splat"
  status = 200
# legacy ical feed for pedalpalooza
[[redirects]]
  from = "/cal/icalpp.php"
  to = "https://api.shift2bikes.org/legacy/cal/new-icalpp.php"
  status = 200
  force = true

# these two are needed for legacy "shareable links" from 2017-early 2019 era
[[redirects]]
  from = "/fun/*"
  to = "/calendar/:splat"
  status = 301
[[redirects]]
  from = "/fun2/*"
  to = "/calendar/:splat"
  status = 301

# we can't translate REALLY legacy links (<2017) - they used some odd format.  
# But let's at least land on the calendar page.
[[redirects]]
  from = "/cal/*"
  to = "/calendar/"
  status = 301


# testing out a special redirect for a URL that someone made up
[[redirects]]
  from = "/calendar/pedalpalooza"
  to = "/pages/pedalpalooza"
  status = 301

  
# remove-add trailing slashes kinda?  fool can't really believe this works :P
[[redirects]]
  from = "/addevent/*"
  to = "/addevent"
  status = 200
[[redirects]]
  from = "/calendar/*"
  to = "/calendar"
  status = 200

# old pedalpalooza page should link to new one
[[redirects]]
  from = "/pedalpalooza"
  to = "/pages/pedalpalooza"
  status = 301
